name: Run LabVIEWCLI on Linux Container

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-labview-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Docker Image from Docker Hub
        run: docker pull docker pull nationalinstruments/labview:2025q3-linux

      - name: Run LabVIEWCLI Operations
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            docker pull nationalinstruments/labview:2025q3-linux \
            bash -c "cd /workspace/examples/integration-into-cicd && chmod +x runlabview.sh && ./runlabview.sh"

